name: Project-Automationchetan_python_RELEASE_API_1730176548837
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectautomationchetanpythonreleaseapi1730176548837
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-10-29 04:37:03'
pipelines:
  pipelines/Pipeline-Automationchetan_RELEASE_API_1730176548837:
    name: Pipeline-Automationchetan_RELEASE_API_1730176548837
    description: null
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-29 04:39:28'
    datasets:
      inputs:
      - datasets/Project-Automationchetan_python_RELEASE_API_1730176548837_dataSet
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/Project-Automationchetan_python_RELEASE_API_1730176548837_dataSet:
    name: Project-Automationchetan_python_RELEASE_API_1730176548837_dataSet
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2024-10-29 04:42:29'
    mode: batch
    physicalDatasets:
      dev_shared:
        fabricId: 9
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2024-10-29 04:42:29'
templates: {}
jobs:
  jobs/Project-Automationchetan_python_RELEASE_API_1730176548837_RELEASE_API_JOB:
    name: Project-Automationchetan_python_RELEASE_API_1730176548837_RELEASE_API_JOB
    description: ''
    fabricUID: 1
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0/1 * * ? * * 2090
    timeout: null
    alerting:
      emails: abhisheks+e2etests@prophecy.io
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/Pipeline-Automationchetan_RELEASE_API_1730176548837
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-10-29 04:43:14'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/Test_Release_Trigger_Gem:
      name: Test_Release_Trigger_Gem
      category: Custom
      subCategory: ''
      description: null
      author: abhisheks+e2etests@prophecy.io
      mode: batch
      files:
      - abhishekse2etestsprophecyioteam_projectautomationchetanpythonreleaseapi1730176548837/gems/Test_Release_Trigger_Gem.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-10-29 04:40:48'
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-29 04:37:03'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-10-29T04:37:03.406888Z'
  name: plibMaven
  version: 8.4.1-SNAPSHOT
  id: '1306954137'
  createdAt: '2024-10-29T04:37:03.406888Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-10-29T04:37:51.614Z'
  name: ProphecyLibsPython
  version: 1.9.24
  id: '81561610'
  createdAt: '2024-10-29T04:37:03.406888Z'
  type: plibPypi
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
  __path: '[0]'
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.2.32
    isDefault: true
    author: null
    createdAt: '2024-10-29 04:36:52'
  '6':
    projectUID: 6
    projectName: python_project
    repositoryPath: gitUri=http://gitserver:3000/ku6kXQiA_team_3/vtmtYhPP_project_6.git&subPath=
    version: python_project/v3.3.12.0
    isDefault: false
    author: null
    createdAt: '2024-10-29 04:36:52'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-10-29 04:36:52'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
